spring:
 datasource:
  url: jdbc:mysql://localhost:3306/lmsdb?createDatabaseIfNotExist=true
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  hibernate:
   naming:
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl